var pcode2state = {
    'Morobo':'Morobo',
    'Kajo-keji':'Kajoo-keji',
    'Lainya':'Lainya',
    'Yei':'Yei',
    'Juba':'Juba',
    'Terekeka':'Terekeka',
    'Magwi':'Magwi',
    'Ikotos':'Ikotos',
    'Kapoeta South':'Kapoeta South',
    'Budi':'Budi',
    'Torit':'Torit',
    'Kapoeta North':'Kapoeta North',
    'Lafon':'Lafon',
    'Kapoeta East':'Kapoeta East',
    'Awerial':'Awerial',
    'Yirol West':'Yirol West',
    'Wulu':'Wulu',
    'Rumbek East':'Rumbek East',
    'Cueibet':'Cueibet',
    'Rumbek North':'Rumbek North',
    'Rumbek Centre':'Rumbek Centre',
    'Yirol East':'Yirol East',
    'Aweil South':'Aweil South',
    'Aweil Centre':'Aweil Centre',
    'Aweil West':'Aweil West',
    'Aweil North':'Aweil North',
    'Aweil East':'Aweil East',
    'Panyijiar':'Panyijiar',
    'Mayendit':'Mayendit',
    'Leer':'Leer',
    'Koch':'Koch',
    'Mayom':'Mayom',
    'Guit':'Guit',
    'Rubkona':'Rubkona',
    'Abiemnhom':'Abiemnhom',
    'Pariang':'Pariang',
    'Abyei region':'Abyei region',
    'Tonj South':'Tonj South',
    'Tonj East':'Tonj East',
    'Tonj North':'Tonj North',
    'Gogrial East':'Gogrial East',
    'Gogrial West':'Gogrial West',
    'Twic':'Twic',
    'Wau':'Wau',
    'Jur River':'Jur River',
    'Raga':'Raga',
    'Maridi':'Maridi',
    'Mundri West':'Mundri West',
    'Mundri East':'Mundri East',
    'Ibba':'Ibba',
    'Yambio':'Yambio',
    'Nzara':'Nzara',
    'Mvolo':'Mvolo',
    'Ezo':'Ezo',
    'Tambura':'Tambura',
    'Nagero':'Nagero',
    'Bor South':'Bor South',
    'Pibor':'Pibor',
    'Twic East':'Twic East',
    'Pochalla':'Pochalla',
    'Duk':'Duk',
    'Uror':'Uror',
    'Akobo':'Akobo',
    'Ayod':'Ayod',
    'Nyirol':'Nyirol',
    'Canal/Pigi':'Canal/Pigi',
    'Fangak':'Fangak',
    'Ulang':'Ulang',
    'Maiwut':'Maiwut',
    'Luakpiny/Nasir':'Luakpiny/Nasir',
    'Longochuk':'Longochuk',
    'Panyikang':'Panyikang',
    'Malakal':'Malakal',
    'Baliet':'Baliet',
    'Fashoda':'Fashoda',
    'Melut':'Melut',
    'Manyo':'Manyo',
    'Renk':'Renk',
    'Maban':'Maban'
}
