var pcode2state = {
    'Al Jabal Al Akhdar': 'Al Jabal Al Akhdar',
    'Al Jabal Al Gharbi':'Al Jabal Al Gharbi',
    'Aljfara':'Aljfara',
    'Aljufra':'Aljufra',
    'Alkufra':'Alkufra',
    'Almargeb':'Almargeb',
    'Almarj':'Almarj',
    'Azzawya':'Azzawya',
    'Benghazi':'Benghazi',
    'Derna':'Derna',
    'Ejdabia':'Ejdabia',
    'Ghat':'Ghat',
    'Misrata':'Misrata',
    'Murzuq':'Murzuq',
    'Nalut':'Nalut',
    'Sebha':'Sebha',
    'Sirt':'Sirt',
    'Tobruk':'Tobruk',
    'Tripoli':'Tripoli',
    'Ubari':'Ubari',
    'Wadi Ashshati':'Wadi Ashshati',
    'Zwara':'Zwara'
}